services:
  worker:
    build: .
    environment:
      SESSION: $SESSION
      API_ID: $API_ID  # defaults to None
      API_HASH: $API_HASH  # defaults to None
      DATABASE_URL: $DATABASE_URI  # defaults to None
      BOT_TOKEN: $BOT_TOKEN # Not mandatory
      LOG_CHANNEL: $LOG_CHANNEL # Not mandatory
      
